# Generated by Django 4.1.6 on 2026-04-20 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch_EXPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, unique=True, verbose_name='task_name')),
                ('EXP', models.CharField(max_length=128, verbose_name='plugin')),
                ('thread_num', models.SmallIntegerField(default=10, verbose_name='thread_num')),
                ('sleep_time', models.SmallIntegerField(default=3, verbose_name='sleep_time')),
                ('target', models.FileField(max_length=128, upload_to='EXP_input/', verbose_name='target')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('status', models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop')], default=3, verbose_name='status')),
                ('process', models.CharField(default='0%', max_length=128, verbose_name='process')),
                ('startTime', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='EXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='plugin name')),
                ('CVE', models.CharField(max_length=128, verbose_name='CVE')),
                ('Type', models.SmallIntegerField(choices=[(1, 'Command Execute'), (2, 'Code Execute'), (3, 'sql inject'), (4, 'information leakage'), (5, 'File upload'), (6, 'File Reading'), (7, 'Directory Traversal'), (8, 'Cross-site request forgery'), (9, 'Identity bypass'), (10, 'weak password'), (11, 'Path leakage'), (12, 'other')], default=1, verbose_name='Type')),
                ('time', models.DateField(blank=True, null=True, verbose_name='Exposure time')),
                ('creat_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('plugin_language', models.SmallIntegerField(choices=[(1, 'python3')], default=1, verbose_name='plugin_language')),
                ('use', models.SmallIntegerField(choices=[(1, 'True'), (2, 'false')], default=1, verbose_name='join use')),
                ('poc_type', models.SmallIntegerField(choices=[(1, 'File upload'), (2, 'Custom Add')], default=1, verbose_name='poc_type')),
                ('poc', models.FileField(max_length=128, upload_to='EXP_plugin/', verbose_name='poc')),
                ('poc_content', models.TextField(blank=True, null=True, verbose_name='poc_content')),
            ],
        ),
        migrations.CreateModel(
            name='EXPTask_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.SmallIntegerField(choices=[(1, 'Single exp'), (2, 'Batch exp')], default=1, verbose_name='task_type')),
                ('task_id', models.IntegerField(verbose_name='task_id')),
                ('plugin_name', models.CharField(default='', max_length=128, verbose_name='plugin_name')),
                ('target', models.CharField(max_length=128, verbose_name='target')),
                ('result', models.CharField(max_length=1000, verbose_name='task result')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='crea time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='fingerPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128, verbose_name='product')),
                ('condition', models.TextField(max_length=128, unique=True, verbose_name='condition')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
            ],
        ),
        migrations.CreateModel(
            name='ProxySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.SmallIntegerField(choices=[(1, 'http')], default=1, verbose_name='proxy_type ')),
                ('proxy_address', models.CharField(max_length=128, verbose_name='proxy_address')),
                ('proxy_port', models.IntegerField(verbose_name='proxy_port')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='crea time')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
            ],
            options={
                'unique_together': {('proxy_type', 'proxy_address', 'proxy_port')},
            },
        ),
        migrations.CreateModel(
            name='EXPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, unique=True, verbose_name='task_name')),
                ('taskType', models.SmallIntegerField(choices=[(1, 'Verify'), (2, 'Attact')], default=1, verbose_name='task_type')),
                ('cmd_input', models.CharField(blank=True, max_length=128, null=True, verbose_name='cmd_input')),
                ('thread_num', models.SmallIntegerField(default=10, verbose_name='thread_num')),
                ('sleep_time', models.SmallIntegerField(default=3, verbose_name='sleep_time')),
                ('current_line', models.IntegerField(default=1, verbose_name='current_line')),
                ('input_type', models.SmallIntegerField(choices=[(1, 'from file'), (2, 'history result')], default=1, verbose_name='input_type')),
                ('target', models.FileField(blank=True, max_length=128, null=True, upload_to='EXP_input/', verbose_name='target')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('status', models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop')], default=3, verbose_name='status')),
                ('process', models.CharField(default='0%', max_length=128, verbose_name='process')),
                ('startTime', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
                ('EXP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.exp', verbose_name='plugin')),
            ],
        ),
        migrations.CreateModel(
            name='cveExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.SmallIntegerField(choices=[(1, 'Verify'), (2, 'Command Execute'), (3, 'Code Execute'), (4, 'File Reading'), (5, 'Attact')], default=1, verbose_name='Type')),
                ('CVE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.exp', verbose_name='plugin')),
            ],
        ),
        migrations.CreateModel(
            name='auto_scan_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, unique=True, verbose_name='task_name')),
                ('thread_num', models.SmallIntegerField(default=10, verbose_name='thread_num')),
                ('sleep_time', models.SmallIntegerField(default=3, verbose_name='sleep_time')),
                ('current_line', models.IntegerField(default=1, verbose_name='current_line')),
                ('target', models.FileField(max_length=128, upload_to='EXP_input/', verbose_name='target')),
                ('Vulnerability_scanning', models.SmallIntegerField(choices=[(1, 'yes'), (0, 'no')], default=0, verbose_name='Vulnerability_scanning')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('status', models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop')], default=3, verbose_name='status')),
                ('startTime', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cybersparker.proxysetting', verbose_name='proxy')),
            ],
        ),
        migrations.CreateModel(
            name='auto_scan_indentify_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='task_id')),
                ('product', models.CharField(max_length=128, verbose_name='product')),
                ('target', models.CharField(max_length=128, verbose_name='target')),
                ('ip', models.CharField(max_length=45, verbose_name='ip')),
                ('protocol', models.CharField(max_length=20, verbose_name='protocol')),
                ('port', models.IntegerField(verbose_name='port')),
                ('country', models.CharField(blank=True, max_length=6, null=True, verbose_name='country')),
                ('area', models.CharField(blank=True, max_length=6, null=True, verbose_name='area')),
                ('area_name_zh', models.CharField(blank=True, max_length=6, null=True, verbose_name='area_name_zh')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='crea time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='status_code')),
                ('header', models.TextField(blank=True, null=True, verbose_name='header')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html')),
            ],
            options={
                'unique_together': {('task_id', 'product', 'target')},
            },
        ),
        migrations.CreateModel(
            name='auto_scan_exp_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='task_id')),
                ('product', models.CharField(default='', max_length=128, verbose_name='product')),
                ('target', models.CharField(max_length=128, verbose_name='target')),
                ('result', models.CharField(max_length=1000, verbose_name='task result')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='crea time')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update time')),
                ('EXP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.exp', verbose_name='EXP_id')),
            ],
        ),
        migrations.CreateModel(
            name='exp_relate_fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.exp', verbose_name='plugin')),
                ('fingerprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.fingerprint', verbose_name='plugin')),
            ],
            options={
                'unique_together': {('EXP_id', 'fingerprint_id')},
            },
        ),
    ]
