# Generated by Django 4.1.6 on 2026-04-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='run_mode',
            field=models.SmallIntegerField(choices=[(1, '线程'), (2, '协程')], default=1, verbose_name='运行方式'),
        ),
    ]
