# Generated by Django 4.1.6 on 2026-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0002_batch_exptask_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='history_files',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='history_files'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (2, 'history vuln assets'), (3, 'history upload files')], default=1, verbose_name='input_type'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='target',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='EXP_input/', verbose_name='target'),
        ),
    ]
