# Generated by Django 4.1.6 on 2026-04-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0003_batch_exptask_history_files_batch_exptask_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='engine_max_assets',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='engine_max_assets'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='engine_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cybersparker.proxysetting', verbose_name='engine_proxy'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='engine_proxy_mode',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'follow engine config'), (1, 'no proxy'), (2, 'force proxy')], default=0, null=True, verbose_name='engine_proxy_mode'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='engine_query',
            field=models.TextField(blank=True, null=True, verbose_name='engine_query'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('fofa', 'fofa'), ('zoomeye', 'zoomeye'), ('quake', 'quake'), ('hunter', 'hunter'), ('shodan', 'shodan')], max_length=20, null=True, verbose_name='engine_type'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (2, 'history vuln assets'), (3, 'history upload files'), (4, 'cyberspace engine')], default=1, verbose_name='input_type'),
        ),
        migrations.CreateModel(
            name='CyberspaceEngineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('fofa', 'fofa'), ('zoomeye', 'zoomeye'), ('quake', 'quake'), ('hunter', 'hunter'), ('shodan', 'shodan')], max_length=20, unique=True, verbose_name='engine_type')),
                ('api_base_url', models.CharField(max_length=255, verbose_name='api_base_url')),
                ('account_email', models.CharField(blank=True, max_length=128, null=True, verbose_name='account_email')),
                ('api_key', models.CharField(max_length=255, verbose_name='api_key')),
                ('use_proxy', models.BooleanField(default=False, verbose_name='use_proxy')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='remark')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='update_time')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cybersparker.proxysetting', verbose_name='proxy')),
            ],
        ),
    ]
