# Generated by Django 4.1.6 on 2026-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0006_add_input_type_5_history_cyberspace_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='reuse_engine_data',
            field=models.BooleanField(default=False, verbose_name='reuse_engine_data'),
        ),
    ]
