# Generated by Django 4.1.6 on 2026-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0008_result_field_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='process',
            field=models.CharField(default='0%', max_length=128, verbose_name='process'),
        ),
    ]
