# Generated by Django 4.1.6 on 2026-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0012_scheduler_runtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='area',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='area_name_zh',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='area_name_zh'),
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='country',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='country'),
        ),
    ]
