# Generated by Django 4.1.6 on 2026-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0013_increase_country_area_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='pause_requested',
            field=models.BooleanField(default=False, verbose_name='pause requested'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='phase',
            field=models.SmallIntegerField(choices=[(1, '正在Web扫描'), (2, '正在漏洞扫描'), (3, '全部完成')], default=3, verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop'), (4, 'pause')], default=3, verbose_name='status'),
        ),
    ]
