# Generated by Django 4.1.6 on 2026-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0014_add_phase_pause_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='http_timeout',
            field=models.SmallIntegerField(default=30, verbose_name='HTTP超时(秒)'),
        ),
    ]
