# Generated by Django 4.1.6 on 2026-05-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0015_add_http_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='engine_max_assets',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='engine_max_assets'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='engine_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_scan_engine_proxy', to='app_cybersparker.proxysetting', verbose_name='engine_proxy'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='engine_proxy_mode',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'follow engine config'), (1, 'no proxy'), (2, 'force proxy')], default=0, null=True, verbose_name='engine_proxy_mode'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='engine_query',
            field=models.TextField(blank=True, null=True, verbose_name='engine_query'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('fofa', 'fofa'), ('zoomeye', 'zoomeye'), ('quake', 'quake'), ('hunter', 'hunter'), ('shodan', 'shodan')], max_length=20, null=True, verbose_name='engine_type'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='history_files',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='history_files'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (3, 'history upload files'), (4, 'cyberspace engine'), (5, 'history cyberspace results')], default=1, verbose_name='input_type'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='reuse_engine_data',
            field=models.BooleanField(default=False, verbose_name='reuse_engine_data'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='http_timeout',
            field=models.SmallIntegerField(default=10, verbose_name='HTTP超时(秒)'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_scan_http_proxy', to='app_cybersparker.proxysetting', verbose_name='proxy'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='target',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='EXP_input/', verbose_name='target'),
        ),
    ]
