# Generated by Django 4.1.6 on 2026-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0017_add_result_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='sleep_time',
            field=models.SmallIntegerField(default=0, verbose_name='sleep_time'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='thread_num',
            field=models.SmallIntegerField(default=100, verbose_name='thread_num'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='sleep_time',
            field=models.SmallIntegerField(default=0, verbose_name='sleep_time'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='thread_num',
            field=models.SmallIntegerField(default=100, verbose_name='thread_num'),
        ),
        migrations.AlterField(
            model_name='exptask',
            name='sleep_time',
            field=models.SmallIntegerField(default=0, verbose_name='sleep_time'),
        ),
        migrations.AlterField(
            model_name='exptask',
            name='thread_num',
            field=models.SmallIntegerField(default=100, verbose_name='thread_num'),
        ),
    ]
