# Generated by Django 4.1.6 on 2026-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0021_alter_auto_scan_indentify_result_cert_common_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='isp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='isp'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='resolved_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='resolved_ip'),
        ),
    ]
