# Generated by Django 4.1.6 on 2026-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0022_add_province_city_isp_resolved_ip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='host'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='uri_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='uri_path'),
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='country'),
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together={('protocol', 'host', 'port', 'uri_path')},
        ),
        migrations.AddIndex(
            model_name='auto_scan_indentify_result',
            index=models.Index(fields=['host'], name='app_cybersparker_host_425615_idx'),
        ),
        migrations.RemoveField(
            model_name='auto_scan_indentify_result',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auto_scan_indentify_result',
            name='area_name_zh',
        ),
        migrations.RemoveField(
            model_name='auto_scan_indentify_result',
            name='resolved_ip',
        ),
    ]
