# Generated by Django 4.1.6 on 2026-05-23 09:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0023_restructure_asset_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirScanDictGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='组名')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='DirScanDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='字典名')),
                ('paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None, verbose_name='路径列表')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(related_name='dicts', to='app_cybersparker.dirscandictgroup', verbose_name='所属组')),
            ],
        ),
    ]
