# Generated by Django 4.1.6 on 2026-05-23 09:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0024_add_dirscan_dict_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together={('protocol', 'host', 'port')},
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='dir_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None, verbose_name='目录产品'),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_dir_products_gin ON app_cybersparker_auto_scan_indentify_result USING GIN (dir_products)",
            reverse_sql="DROP INDEX IF EXISTS idx_dir_products_gin",
        ),
    ]
