# Generated by Django 4.1.6 on 2026-05-23 09:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0025_restructure_asset_unique_3tuple'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_scan_directory_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='task_id')),
                ('protocol', models.CharField(max_length=20, verbose_name='protocol')),
                ('host', models.CharField(max_length=255, verbose_name='host')),
                ('port', models.IntegerField(verbose_name='port')),
                ('uri_path', models.CharField(max_length=512, verbose_name='uri_path')),
                ('ip', models.CharField(blank=True, default='', max_length=45, verbose_name='ip')),
                ('target', models.CharField(blank=True, default='', max_length=128, verbose_name='target')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='status_code')),
                ('header', models.TextField(blank=True, null=True, verbose_name='header')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html')),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None, verbose_name='产品')),
                ('favicon', models.TextField(blank=True, null=True, verbose_name='favicon')),
                ('favicon_md5', models.CharField(blank=True, max_length=32, null=True, verbose_name='favicon_md5')),
                ('cert_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='cert_org')),
                ('cert_org_unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='cert_org_unit')),
                ('cert_common_name', models.TextField(blank=True, null=True, verbose_name='cert_common_name')),
                ('cert_serial', models.CharField(blank=True, max_length=128, null=True, verbose_name='cert_serial')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='DirScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, unique=True, verbose_name='任务名')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='描述')),
                ('source_tasks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='源任务ID列表')),
                ('source_all', models.BooleanField(default=False, verbose_name='全选所有任务')),
                ('pool_size', models.SmallIntegerField(default=500, verbose_name='活跃池大小')),
                ('concurrency', models.SmallIntegerField(default=20, verbose_name='并发数')),
                ('max_body_size', models.IntegerField(default=524288, verbose_name='最大body大小(字节)')),
                ('max_truncate_size', models.IntegerField(default=1048576, verbose_name='流式截断上限(字节)')),
                ('enable_vuln_scan', models.BooleanField(default=True, verbose_name='启用漏洞扫描')),
                ('vuln_thread_num', models.SmallIntegerField(default=40, verbose_name='漏洞扫描线程数')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('phase', models.SmallIntegerField(default=0, verbose_name='阶段')),
                ('progress_total', models.IntegerField(default=0, verbose_name='总进度')),
                ('progress_done', models.IntegerField(default=0, verbose_name='已完成进度')),
                ('shuffle_file', models.CharField(blank=True, max_length=512, verbose_name='快照文件')),
                ('file_pos', models.IntegerField(default=0, verbose_name='文件读取位置')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='心跳时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('dispatch_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='调度令牌')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='所有者')),
                ('queued', models.BooleanField(default=False, verbose_name='已入队')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dicts', models.ManyToManyField(related_name='tasks', to='app_cybersparker.dirscandict', verbose_name='字典')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cybersparker.proxysetting', verbose_name='代理')),
            ],
        ),
        migrations.AddIndex(
            model_name='auto_scan_directory_result',
            index=models.Index(fields=['task_id'], name='app_cybersparker_task_id_4236c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auto_scan_directory_result',
            index=models.Index(fields=['host', 'port', 'protocol'], name='app_cybersparker_host_983251_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_directory_result',
            unique_together={('protocol', 'host', 'port', 'uri_path')},
        ),
    ]
