# Generated by Django 4.1.6 on 2026-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0026_add_dirscan_task_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirscantask',
            name='concurrency',
            field=models.IntegerField(default=20, verbose_name='并发数'),
        ),
        migrations.AlterField(
            model_name='dirscantask',
            name='pool_size',
            field=models.IntegerField(default=500, verbose_name='活跃池大小'),
        ),
    ]
