# Generated by Django 4.1.6 on 2026-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0027_fix_pool_concurrency_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirscantask',
            name='phase',
            field=models.SmallIntegerField(choices=[(0, '未初始化'), (1, 'Web扫描'), (2, '漏洞扫描'), (3, '回写清理')], default=0, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='dirscantask',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待执行'), (1, '运行中'), (2, '暂停中'), (3, '已停止'), (4, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
