# Generated by Django 4.1.6 on 2026-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0028_add_dirscan_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='cmd_input',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='cmd_input'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='task_type',
            field=models.SmallIntegerField(choices=[(1, 'Verify'), (2, 'Attact')], default=1, verbose_name='task_type'),
        ),
    ]
