# Generated by Django 4.1.6 on 2026-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0029_add_batch_task_type_cmdinput'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auto_scan_indentify_result',
            index=models.Index(fields=['task_id'], name='app_cybersparker_task_id_2ed002_idx'),
        ),
    ]
