# Generated by Django 4.1.6 on 2026-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0030_add_task_id_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirscantask',
            name='max_body_size',
            field=models.IntegerField(default=3145728, verbose_name='最大body大小(字节)'),
        ),
    ]
