# Generated by Django 4.1.6 on 2026-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0031_change_dirscan_max_body_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirscantask',
            name='concurrency',
            field=models.IntegerField(default=100, verbose_name='并发数'),
        ),
        migrations.AlterField(
            model_name='dirscantask',
            name='pool_size',
            field=models.IntegerField(default=200, verbose_name='活跃池大小'),
        ),
        migrations.AlterField(
            model_name='dirscantask',
            name='vuln_thread_num',
            field=models.SmallIntegerField(default=60, verbose_name='漏洞扫描线程数'),
        ),
    ]
