# Generated by Django 4.1.6 on 2026-05-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0034_export_favicon_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_scan_directory_result',
            name='favicon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='auto_scan_directory_result',
            name='favicon_md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='favicon_md5'),
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='favicon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='favicon_md5',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='favicon_md5'),
        ),
    ]
