# Generated by Django 4.1.6 on 2026-05-24 14:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0036_pg_bigm_tsvector_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('global', '全局检索'), ('task', '任务检索')], max_length=16, verbose_name='任务类型')),
                ('task_id', models.IntegerField(blank=True, null=True, verbose_name='自动扫描任务ID')),
                ('task_name', models.CharField(blank=True, max_length=256, verbose_name='任务名')),
                ('search_string', models.TextField(blank=True, verbose_name='检索条件')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None, verbose_name='导出字段')),
                ('include_vuln_result', models.BooleanField(default=False, verbose_name='包含漏洞验证结果')),
                ('export_limit', models.IntegerField(blank=True, null=True, verbose_name='导出条数上限')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=16, verbose_name='状态')),
                ('csv_file', models.CharField(blank=True, max_length=512, verbose_name='CSV文件路径')),
                ('total_rows', models.IntegerField(blank=True, null=True, verbose_name='导出总行数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('creatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
