# Generated by Django 4.1.6 on 2026-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0037_add_export_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeyeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255, verbose_name='API Token')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ceye 配置',
                'verbose_name_plural': 'ceye 配置',
            },
        ),
    ]
