# Generated by Django 4.1.6 on 2026-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0038_ceye_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxysetting',
            name='proxy_type',
            field=models.SmallIntegerField(choices=[(1, 'http'), (4, 'socks5')], default=1, verbose_name='proxy_type '),
        ),
    ]
