# Generated by Django 4.1.6 on 2026-05-27 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0039_alter_proxysetting_proxy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_plugin_proxy', to='app_cybersparker.proxysetting', verbose_name='插件代理'),
        ),
    ]
