# Generated by Django 4.1.6 on 2026-05-27 05:32

from django.db import migrations, models


def migrate_source_all_to_input_mode(apps, schema_editor):
    """source_all=True → input_mode=1, source_all=False → input_mode=0"""
    DirScanTask = apps.get_model('app_cybersparker', 'DirScanTask')
    DirScanTask.objects.filter(source_all=True).update(input_mode=1)
    DirScanTask.objects.filter(source_all=False).update(input_mode=0)


def reverse_input_mode_to_source_all(apps, schema_editor):
    """input_mode=1 → source_all=True, else → source_all=False"""
    DirScanTask = apps.get_model('app_cybersparker', 'DirScanTask')
    DirScanTask.objects.filter(input_mode=1).update(source_all=True)
    DirScanTask.objects.exclude(input_mode=1).update(source_all=False)


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0040_batch_task_plugin_proxy'),
    ]

    operations = [
        # 1. Add new fields first
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='frozen_max_id',
            field=models.IntegerField(default=0, verbose_name='冻结时资产max_id'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='last_id',
            field=models.IntegerField(default=0, verbose_name='keyset游标'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='parsed_query',
            field=models.JSONField(blank=True, null=True, verbose_name='冻结的解析树'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='search_query',
            field=models.TextField(blank=True, null=True, verbose_name='检索语句'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='frozen_max_id',
            field=models.IntegerField(default=0, verbose_name='冻结时资产max_id'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='last_id',
            field=models.IntegerField(default=0, verbose_name='keyset游标'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='parsed_query',
            field=models.JSONField(blank=True, null=True, verbose_name='冻结的解析树'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='search_query',
            field=models.TextField(blank=True, null=True, verbose_name='检索语句'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='frozen_max_id',
            field=models.IntegerField(default=0, verbose_name='冻结时资产max_id'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='input_mode',
            field=models.SmallIntegerField(choices=[(0, '手动选择任务'), (1, '全选所有任务'), (2, '从检索语句导入')], default=0, verbose_name='输入模式'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='parsed_query',
            field=models.JSONField(blank=True, null=True, verbose_name='冻结的解析树'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='search_query',
            field=models.TextField(blank=True, null=True, verbose_name='检索语句'),
        ),

        # 2. Data migration: copy source_all values to input_mode
        migrations.RunPython(
            migrate_source_all_to_input_mode,
            reverse_input_mode_to_source_all,
        ),

        # 3. Remove source_all after data is migrated
        migrations.RemoveField(
            model_name='dirscantask',
            name='source_all',
        ),

        # 4. Alter input_type choices for auto_scan_tasks and batch_exptask
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (3, 'history upload files'), (4, 'cyberspace engine'), (5, 'history cyberspace results'), (6, '从检索语句导入')], default=1, verbose_name='input_type'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (2, 'history vuln assets'), (3, 'history upload files'), (4, 'cyberspace engine'), (5, 'history cyberspace results'), (6, '从检索语句导入')], default=1, verbose_name='input_type'),
        ),
    ]
