# Generated by Django 4.1.6 on 2026-05-27 08:38

from django.db import migrations, models
import django.db.models.deletion


def copy_task_id_to_relation(apps, schema_editor):
    """将 auto_scan_indentify_result.task_id 迁移到 AssetTaskRelation 表"""
    AutoScanIndentifyResult = apps.get_model("app_cybersparker", "auto_scan_indentify_result")
    AssetTaskRelation = apps.get_model("app_cybersparker", "AssetTaskRelation")

    rows = AutoScanIndentifyResult.objects.exclude(task_id__isnull=True).values_list("task_id", "id")
    relations = [
        AssetTaskRelation(task_id=task_id, identify_result_id=result_id)
        for task_id, result_id in rows
    ]
    if relations:
        AssetTaskRelation.objects.bulk_create(relations, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0041_add_search_query_input_type'),
    ]

    operations = [
        # 1. 创建关系表
        migrations.CreateModel(
            name='AssetTaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
            ],
        ),
        # 2. 添加外键 + 索引 + 唯一约束
        migrations.AddField(
            model_name='assettaskrelation',
            name='identify_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_relations', to='app_cybersparker.auto_scan_indentify_result'),
        ),
        migrations.AddIndex(
            model_name='assettaskrelation',
            index=models.Index(fields=['task_id', 'identify_result_id'], name='idx_task_asset'),
        ),
        migrations.AlterUniqueTogether(
            name='assettaskrelation',
            unique_together={('task_id', 'identify_result_id')},
        ),
        # 3. 数据迁移：复制现有 task_id 到关系表
        migrations.RunPython(copy_task_id_to_relation, reverse_code=migrations.RunPython.noop),
        # 4. 删除 auto_scan_indentify_result 的 task_id 字段和索引
        migrations.RemoveIndex(
            model_name='auto_scan_indentify_result',
            name='app_cybersparker_task_id_2ed002_idx',
        ),
        migrations.RemoveField(
            model_name='auto_scan_indentify_result',
            name='task_id',
        ),
    ]
