# Generated by Django 4.1.6 on 2026-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0042_asset_task_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exp',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', '严重'), ('high', '高危'), ('medium', '中危'), ('low', '低危'), ('info', '信息')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='exp',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exps', to='app_cybersparker.tag'),
        ),
    ]
