# Generated by Django 4.1.6 on 2026-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0043_exp_severity_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='exp_select_mode',
            field=models.SmallIntegerField(choices=[(1, '手动选择'), (2, '按条件筛选')], default=1, verbose_name='选EXP方式'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='filter_logic',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3, verbose_name='筛选逻辑'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='severity_filter',
            field=models.JSONField(blank=True, null=True, verbose_name='危害等级筛选'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='tag_filter',
            field=models.JSONField(blank=True, null=True, verbose_name='标签筛选'),
        ),
    ]
