# Generated by Django 4.1.6 on 2026-06-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0046_asset_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirscantask',
            name='pause_requested',
            field=models.BooleanField(default=False, verbose_name='暂停请求'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='stop_requested',
            field=models.BooleanField(default=False, verbose_name='停止请求'),
        ),
    ]
