# Generated by Django 4.1.6 on 2026-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0047_add_dirscan_pause_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirscantask',
            name='sleep_time',
            field=models.SmallIntegerField(default=0, verbose_name='休眠时间(秒)'),
        ),
    ]
