# Generated by Django 4.1.6 on 2026-06-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0048_add_dirscan_sleep_time'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auto_scan_directory_result',
            new_name='app_cybersp_task_id_4ab207_idx',
            old_name='app_cybersparker_task_id_4236c3_idx',
        ),
        migrations.RenameIndex(
            model_name='auto_scan_directory_result',
            new_name='app_cybersp_host_6074d9_idx',
            old_name='app_cybersparker_host_983251_idx',
        ),
        migrations.RenameIndex(
            model_name='auto_scan_exp_result',
            new_name='app_cybersp_task_id_29adc7_idx',
            old_name='app_cybersparker_task_id_2bfc1d_idx',
        ),
        migrations.RenameIndex(
            model_name='auto_scan_indentify_result',
            new_name='app_cybersp_ip_a3015a_idx',
            old_name='app_cybersparker_ip_6e13e3_idx',
        ),
        migrations.RenameIndex(
            model_name='auto_scan_indentify_result',
            new_name='app_cybersp_host_a73a00_idx',
            old_name='app_cybersparker_host_425615_idx',
        ),
    ]
