# Generated by Django 4.1.6 on 2026-06-07 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0049_rename_indexes_for_app_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='配置名称')),
                ('model_id', models.CharField(max_length=128, verbose_name='模型 ID')),
                ('api_url', models.URLField(max_length=512, verbose_name='API 地址')),
                ('api_key', models.CharField(max_length=512, verbose_name='API Key')),
                ('model_type', models.CharField(choices=[('thinking', '思考模型'), ('vision', '识图模型')], max_length=16, verbose_name='模型类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'db_table': 'ai_model_config',
            },
        ),
    ]
