# Generated by Django 4.1.6 on 2026-06-07 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0050_ai_model_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoCGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='任务标题')),
                ('task_type', models.CharField(choices=[('url_crawl', 'URL爬取'), ('file_upload', '上传文件')], max_length=16, verbose_name='任务类型')),
                ('plugin_language', models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Nuclei YAML')], verbose_name='插件类型')),
                ('urls', models.TextField(blank=True, verbose_name='URL列表（JSON数组）')),
                ('uploaded_file', models.CharField(blank=True, max_length=512, verbose_name='上传文件路径')),
                ('material_dir', models.CharField(blank=True, max_length=512, verbose_name='资料目录')),
                ('crawl_status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('success', '提取成功'), ('failed', '提取失败')], default='pending', max_length=16, verbose_name='资料提取状态')),
                ('crawl_detail', models.TextField(blank=True, verbose_name='爬取详情（JSON）')),
                ('task_description_prompt', models.TextField(blank=True, verbose_name='任务说明提示词')),
                ('plugin_spec_prompt', models.TextField(blank=True, verbose_name='插件规范提示词')),
                ('reference_material_prompt', models.TextField(blank=True, verbose_name='参考资料提示词')),
                ('custom_prompt', models.TextField(blank=True, verbose_name='用户自定义提示词')),
                ('generated_poc_content', models.TextField(blank=True, verbose_name='生成的PoC代码')),
                ('generated_metadata', models.TextField(blank=True, verbose_name='生成的元数据（JSON）')),
                ('generated_extra_info', models.TextField(blank=True, verbose_name='生成的额外信息')),
                ('saved_to_exp', models.BooleanField(default=False, verbose_name='已保存到EXP库')),
                ('saved_exp_id', models.IntegerField(blank=True, null=True, verbose_name='保存的EXP ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('crawling', '资料提取中'), ('ready', '待生成'), ('generating', '生成中'), ('generated', '生成完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='任务状态')),
                ('celery_task_id', models.CharField(blank=True, max_length=128, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cybersparker.proxysetting')),
                ('thinking_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poc_gen_tasks', to='app_cybersparker.aimodelconfig')),
                ('vision_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_gen_vision_tasks', to='app_cybersparker.aimodelconfig')),
            ],
            options={
                'verbose_name': 'PoC 生成任务',
                'db_table': 'poc_generation_task',
            },
        ),
    ]
