# Generated by Django 4.1.6 on 2026-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0051_poc_generation_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocgenerationtask',
            name='plugin_language',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Python'), (2, 'Nuclei YAML')], null=True, verbose_name='插件类型'),
        ),
    ]
