# Generated by Django 4.1.6 on 2026-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0052_plugin_language_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_exptask',
            name='http_timeout',
            field=models.SmallIntegerField(default=10, verbose_name='HTTP超时(秒)'),
        ),
    ]
