# Generated by Django 4.1.6 on 2026-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0053_add_batch_http_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_scan_directory_result',
            name='target',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='pocgenerationtask',
            name='task_type',
            field=models.CharField(choices=[('url_crawl', 'URL爬取'), ('file_upload', '上传文件'), ('text_input', '直接输入文本')], max_length=16, verbose_name='任务类型'),
        ),
    ]
