# Generated by Django 4.1.6 on 2026-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0054_extend_dirscan_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_directory_result',
            name='content_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='响应体大小(字节)'),
        ),
    ]
