# Generated by Django 4.1.6 on 2026-06-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0056_add_task_type_to_auto_scan_exp_result'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auto_scan_exp_result',
            name='app_cybersp_task_ty_819a0c_idx',
        ),
        migrations.AddIndex(
            model_name='auto_scan_exp_result',
            index=models.Index(fields=['task_type', 'target', 'task_id'], name='app_cybersp_task_ty_4a0378_idx'),
        ),
    ]
