# Generated by Django 4.1.6 on 2026-06-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0058_add_identify_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='CVE',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='CVE'),
        ),
    ]
