# Generated by Django 4.1.6 on 2026-06-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0059_exp_cve_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='task_args',
            field=models.TextField(blank=True, null=True, verbose_name='自定义参数(JSON)'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='task_args',
            field=models.TextField(blank=True, null=True, verbose_name='自定义参数(JSON)'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='task_args',
            field=models.TextField(blank=True, null=True, verbose_name='自定义参数(JSON)'),
        ),
    ]
