# Generated by Django 4.1.6 on 2026-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0060_task_args_custom_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirscantask',
            name='http_timeout',
            field=models.SmallIntegerField(default=10, verbose_name='HTTP超时(秒)'),
        ),
    ]
