# Generated by Django 4.1.6 on 2026-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0062_extend_vulnerability_scanning_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='condition',
            field=models.TextField(unique=True, verbose_name='condition'),
        ),
    ]
