# Generated by Django 4.1.6 on 2026-06-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0063_remove_fingerprint_condition_max_length'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('app_cybersparker', 'auto_scan_indentify_result').objects.filter(uri_path='/').update(uri_path=''),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together={('protocol', 'host', 'port', 'uri_path')},
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='source_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'auto_scan'), (2, 'fscanx')], default=1, null=True, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='conflict_strategy',
            field=models.SmallIntegerField(choices=[(1, '覆盖'), (2, '跳过')], default=1, verbose_name='冲突策略'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='fscanx_file',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='EXP_input/', verbose_name='fscanx输出文件'),
        ),
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='input_type',
            field=models.SmallIntegerField(choices=[(1, 'from file'), (2, 'fscanx输出文件'), (3, 'history upload files'), (4, 'cyberspace engine'), (5, 'history cyberspace results'), (6, '从检索语句导入')], default=1, verbose_name='input_type'),
        ),
        migrations.CreateModel(
            name='fscanx_service_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=20, verbose_name='协议')),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('result_type', models.SmallIntegerField(choices=[(1, '弱口令'), (2, 'ftp文件清单'), (3, 'smb文件清单'), (4, 'os系统信息'), (5, 'rdp信息'), (6, '漏洞资产信息')], verbose_name='成果类型')),
                ('result', models.TextField(verbose_name='结果内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cybersparker.auto_scan_tasks', verbose_name='任务')),
            ],
        ),
        migrations.AddIndex(
            model_name='fscanx_service_detail',
            index=models.Index(fields=['task_id', 'host', 'port'], name='app_cybersp_task_id_e41516_idx'),
        ),
    ]
