# Generated by Django 4.1.6 on 2026-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0065_add_netinfo_result_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fscanx_service_detail',
            name='result_type',
            field=models.SmallIntegerField(choices=[(1, '弱口令'), (2, 'ftp文件清单'), (3, 'smb文件清单'), (4, 'os系统信息'), (5, 'rdp信息'), (6, '漏洞资产信息'), (7, '网卡信息'), (8, 'NetBios主机名'), (9, 'MS17-010漏洞')], verbose_name='成果类型'),
        ),
    ]
