# Generated by Django 4.1.6 on 2026-06-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0066_add_netbios_and_ms17010'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='copyright',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='copyright'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='icp',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='icp'),
        ),
        migrations.AlterField(
            model_name='fscanx_service_detail',
            name='result_type',
            field=models.SmallIntegerField(choices=[(1, '弱口令'), (2, 'ftp文件清单'), (3, 'smb文件清单'), (4, 'os系统信息'), (5, 'rdp信息'), (6, '漏洞资产信息'), (7, '网卡信息'), (8, 'NetBios主机名'), (9, 'MS17-010漏洞'), (10, '未授权访问')], verbose_name='成果类型'),
        ),
        migrations.AddIndex(
            model_name='auto_scan_indentify_result',
            index=models.Index(fields=['copyright'], name='app_cybersp_copyrig_f02be0_idx'),
        ),
        migrations.AddIndex(
            model_name='auto_scan_indentify_result',
            index=models.Index(fields=['icp'], name='app_cybersp_icp_57c247_idx'),
        ),
    ]
