# Generated by Django 4.1.6 on 2026-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0068_replace_copyright_icp_btree_with_gin'),
    ]

    operations = [
        # 0068 已通过 DROP INDEX IF EXISTS 删除了这两个索引，此处仅做状态标记
        migrations.RunSQL(
            sql="SELECT 1",
            reverse_sql="SELECT 1",
            state_operations=[
                migrations.RemoveIndex(
                    model_name='auto_scan_indentify_result',
                    name='app_cybersp_copyrig_f02be0_idx',
                ),
                migrations.RemoveIndex(
                    model_name='auto_scan_indentify_result',
                    name='app_cybersp_icp_57c247_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='auto_scan_indentify_result',
            name='icp',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='icp'),
        ),
    ]
