# Generated by Django 4.1.6 on 2026-06-19 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0070_cert_fields_gin_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=512, verbose_name='原始文件名')),
                ('stored_name', models.CharField(max_length=512, unique=True, verbose_name='磁盘文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开访问')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '托管文件',
                'db_table': 'hosted_file',
            },
        ),
    ]
