# Generated by Django 4.1.6 on 2026-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0071_hosted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedfile',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
