# Generated by Django 4.1.6 on 2026-06-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cybersparker', '0072_hosted_file_note'),
    ]

    def init_super_admin(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        UserProfile = apps.get_model('app_cybersparker', 'UserProfile')
        if not User.objects.filter(username='admin').exists():
            user = User.objects.create_superuser(
                username='admin',
                password='admin',
                email='',
                is_active=True,
            )
            UserProfile.objects.create(user=user, role='super_admin')

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '普通管理员'), ('user', '普通用户')], default='user', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'db_table': 'user_profile',
            },
        ),
        migrations.RunPython(init_super_admin, migrations.RunPython.noop),
    ]
