# Generated by Django 4.1.6 on 2026-06-20 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0073_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='auto_scan_directory_result',
            name='root_identify_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directory_results', to='app_cybersparker.auto_scan_indentify_result'),
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_directory_result',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auto_scan_directory_result',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone'),
        ),
        migrations.AddField(
            model_name='auto_scan_indentify_result',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone'),
        ),
        migrations.AddField(
            model_name='auto_scan_tasks',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone'),
        ),
        migrations.AddField(
            model_name='batch_exptask',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone'),
        ),
        migrations.AddField(
            model_name='dirscantask',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone'),
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_directory_result',
            unique_together={('zone', 'protocol', 'host', 'port', 'uri_path')},
        ),
        migrations.AlterUniqueTogether(
            name='auto_scan_indentify_result',
            unique_together={('zone', 'protocol', 'host', 'port', 'uri_path')},
        ),
        migrations.CreateModel(
            name='AssetRootBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('identify_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_bindings', to='app_cybersparker.auto_scan_indentify_result')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_cybersparker.assetzone')),
            ],
            options={
                'unique_together': {('zone', 'protocol', 'host', 'port')},
            },
        ),
    ]
