# Generated by Django 4.1.6 on 2026-06-20 09:21

from django.db import migrations
from django.utils import timezone


def insert_system_zone(apps, schema_editor):
    AssetZone = apps.get_model("app_cybersparker", "AssetZone")
    AssetZone.objects.create(
        code="public", name="公网", is_system=True,
        created_at=timezone.now(),
    )


def backfill_zone_fks(apps, schema_editor):
    AssetZone = apps.get_model("app_cybersparker", "AssetZone")
    public = AssetZone.objects.get(code="public")

    models_to_backfill = [
        ("auto_scan_indentify_result", "zone_id"),
        ("auto_scan_tasks", "zone_id"),
        ("batch_EXPTask", "zone_id"),
        ("DirScanTask", "zone_id"),
        ("auto_scan_directory_result", "zone_id"),
    ]

    for model_name, field_name in models_to_backfill:
        Model = apps.get_model("app_cybersparker", model_name)
        Model.objects.filter(**{f"{field_name}__isnull": True}).update(
            **{field_name: public.id}
        )


def reverse_backfill(apps, schema_editor):
    """回滚：设置所有 zone FK 为 NULL（仅回填的逆向，不删系统区域）"""
    models_to_clear = [
        "auto_scan_indentify_result",
        "auto_scan_tasks",
        "batch_EXPTask",
        "DirScanTask",
        "auto_scan_directory_result",
    ]
    for model_name in models_to_clear:
        Model = apps.get_model("app_cybersparker", model_name)
        Model.objects.all().update(zone_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0074_assetzone_models'),
    ]

    operations = [
        migrations.RunPython(insert_system_zone, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(backfill_zone_fks, reverse_code=reverse_backfill),
    ]
