# Generated by Django 4.1.6 on 2026-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0075_backfill_assetzone'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS idx_html_trgm",
            reverse_sql="CREATE INDEX IF NOT EXISTS idx_html_trgm ON app_cybersparker_auto_scan_indentify_result USING GIN (html gin_trgm_ops)",
        ),
    ]
