# Generated by Django 4.1.6 on 2026-06-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0076_drop_dead_html_trgm'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS idx_task_asset",
            reverse_sql="CREATE INDEX IF NOT EXISTS idx_task_asset ON app_cybersparker_assettaskrelation (task_id, identify_result_id)",
        ),
    ]
