# Generated by Django 4.1.6 on 2026-06-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0077_drop_duplicate_task_asset_index'),
    ]

    operations = [
        # province/city/isp — 中文模糊搜索（pg_bigm 2-gram 切分）
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_province_upper_bigm ON app_cybersparker_auto_scan_indentify_result USING GIN (UPPER(province) gin_bigm_ops)",
            reverse_sql="DROP INDEX IF EXISTS idx_province_upper_bigm",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_city_upper_bigm ON app_cybersparker_auto_scan_indentify_result USING GIN (UPPER(city) gin_bigm_ops)",
            reverse_sql="DROP INDEX IF EXISTS idx_city_upper_bigm",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_isp_upper_bigm ON app_cybersparker_auto_scan_indentify_result USING GIN (UPPER(isp) gin_bigm_ops)",
            reverse_sql="DROP INDEX IF EXISTS idx_isp_upper_bigm",
        ),
        # cert_serial — 精确匹配（B-tree）
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS idx_cert_serial ON app_cybersparker_auto_scan_indentify_result (cert_serial)",
            reverse_sql="DROP INDEX IF EXISTS idx_cert_serial",
        ),
    ]
