# Generated by Django 4.1.6 on 2026-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0079_zone_not_null'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assettaskrelation',
            name='idx_task_asset',
        ),
        migrations.AddField(
            model_name='exporttask',
            name='zone_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='扫描区域ID'),
        ),
    ]
