# Generated by Django 4.1.6 on 2026-06-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0080_add_export_task_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocgenerationtask',
            name='api_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_api_proxy', to='app_cybersparker.proxysetting', verbose_name='AI API代理'),
        ),
        migrations.AlterField(
            model_name='pocgenerationtask',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_crawl_proxy', to='app_cybersparker.proxysetting', verbose_name='URL爬取代理'),
        ),
    ]
