# Generated by Django 4.1.6 on 2026-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybersparker', '0081_add_poc_api_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_scan_tasks',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop'), (4, 'pause')], db_index=True, default=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='batch_exptask',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'finish'), (2, 'running'), (3, 'stop'), (4, 'pause')], db_index=True, default=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='exptask_result',
            name='task_id',
            field=models.IntegerField(db_index=True, verbose_name='task_id'),
        ),
    ]
